[package]
name = "FFsynTh"
description = ""
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
license-file = "LICENSE"

[dependencies]
cpal = { version = "0.18", features = ["pipewire"] }
rustfft = "6"
ringbuf = "0.4"
ratatui = "0.29"
crossterm = "0.29"
signal-hook = "0.3"
ctrlc = "3"
once_cell = "1"
rand = "0.9"